server:
  port: 8081

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/order-service

product-service:
  url: http://product-service:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true