server:
  port: 8080

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/product-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true