name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build Product Service
      run: |
        cd product-service
        mvn clean package -DskipTests
    
    - name: Build Order Service
      run: |
        cd order-service
        mvn clean package -DskipTests
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Product Service Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./product-service
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
    
    - name: Build and push Order Service Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./order-service
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
    
    # Add deployment steps here based on your environment
    # e.g., deploy to Kubernetes cluster or server via SSH